[package]
name = "byond-get-cli"
version = "0.3.0"
authors = ["Lucy <lucy@absolucy.moe>"]
edition = "2024"
license = "Zlib"

[dependencies]
byond-get = { path = ".." }
clap = { version = "4", features = ["derive"] }
color-eyre = "0.6"
